### DISCUSSION TITLE
Changing to a different font family

### DISCUSSION THREAD

**Discussion by Fastidious** [Henning16/typora-gitbook-theme#23] [General]
What is the recommended, or easier, step to change the default Roboto font to other of my preference/liking?

**Comment by h16nning** [comment]
Hello @Fastidious,
I would consider creating a user.css file. Let's say you would like to modify the font of the azure variant. For that you would create a new file called `gitbook-azure.user.css` and place into the themes folder (just alongside all of the other css files).

You would put the following code inside of that file:

```css
:root {
  --font-family: "your font family for text, ui etc.";
  --code-font-family: "your font family for code blocks, source mode etc.";
  --monospace: "your font family for inline code";
}
```

This overrides the css variables which are specified in the css file of the theme. I am using no hard-coded font family properties, everything relies on these variables.

Of course, you have to make sure that the font is either installed on your device or you have to import it.

You can proceed by creating two more files - `gitbook-teal.user.css` and `gitbook-slate.user.css` - in which you put the same code.

*Alternative: You could also change these variables directly within the `gitbook-azure.css`, `gitbook-teal.css` etc. files. The `:root` rule is right at the top. However, this solution would require you to change these variables when you choose to update the theme. If you know that you won't do that, this option is probably just as comfortable as the other one.*

With that being said, I can't guarantee you that the theme will look good with every font. I would make sure that the font provides also bolder font weights, which are used quite extensively by this theme.

I hope this is helpful!
